VDMS_ROOT_PATH = "/opt/vdms"

source_files = "src/vdms_converter.cpp"

env = Environment(
    CXXFLAGS = "-std=c++11 -fexceptions -g -fpermissive",
    CPPPATH = [
        "inc",
        "/usr/include",
        "/usr/include/jsoncpp",
        "/usr/local/include/opencv4",
	VDMS_ROOT_PATH,
        VDMS_ROOT_PATH + "/client/cpp",
        VDMS_ROOT_PATH + "/utils/include",
    ],
    LIBPATH = [
        "/usr/local/lib",
        VDMS_ROOT_PATH + "/utils",
        VDMS_ROOT_PATH + "/client/cpp"
    ],
    LIBS = [
        "vdms-utils",
        "jsoncpp",
        "vdms-client",
        "opencv_core",
        "opencv_highgui",
        "opencv_imgcodecs",
        "opencv_imgproc",
        "opencv_features2d",
        "opencv_video",
        "opencv_videoio"
       ]
)

env.SharedLibrary("vdms_converter", source_files)
